DATA_PATH="data"
UNNORM_DATA_PATH="UNNORM.npy"
NORM_DATA_PATH="NORM_DATA_PATH.npy"
PRETRAIN=True
DATA_CHANNEL=3
DAE_ENCODER_SIZES=[32,32,64,64]
DAE_DECODER_SIZES=[64,64,32,32]
BVAE_ENCODER_SIZES=[32,32,64,64]
BVAE_DECODER_SIZES=[64,64,32,32]
DAE_ENCODER_ACTIVATION=[True,True,True,True]
DAE_DECODER_ACTIVATION=[True,True,True,False]
BVAE_ENCODER_ACTIVATION=[True,True,True,True]
BVAE_DECODER_ACTIVATION=[True,True,True,False]
DAE_BOTTLENECKS_SIZE=100
DAE_lr=0.001
DAE_eps=0.00000001
DAE_PRETRAIN=True
TRAIN_SIZE=10000
generator_params = {'batch_size': 100,
          'shuffle': True,
          'num_workers': 3
          }
DAE_CHECKPOINT="DAE_LOG"
DAE_LOG="DAE_LOG/DAE_LOG.txt"
DAE_TRAIN_EPOCH=2000
DAE_LOAD_PATH"DAE_LOG/"+str(DAE_TRAIN_EPOCH)+".pt"
BVAE_BETA=53
LATENT_DIM=32
BVAE_EPS=0.00000001
BVAE_LR=0.0001
BVAE_LOAD_PATH="BVAE_LOG"+str(BVAE_TRAIN_EPOCH)+".pt"
VIS_RECON_PATH="VIS_RECON"
VIS_LATENT_TRAVERSAL="LATENT_TRAVERSAL"